### ISSUE TITLE
missing final output files

### ISSUE THREAD

**Issue by kaylahardwick** [maohlzj/SINE_Scan#1]
Hello,

I am using SINE_Scan to identify signs in a non-model organism genome assembly. I ran SINE_Scan in 123 mode using the following command:

perl SINE_Scan_process.pl -s 123 -g $GENOME -d temp -z final.out -o assembly -k 40 1>SINE_Scan_aug14.log 2>SINE_Scan_aug14.err

Sine_Scan reports that it is finished ("SINE_Scan pipeline finished. Running mode=123."). However, I don't see the output directory that I specified with the -z option, nor can I find any gff files that might indicate that step 3 was completed. In addition, while Sine_Scan was running, I got the following error message:

"Modification of non-creatable array value attempted, subscript -1 at ./PL_pipeline/RG_boundary.pl line 117, <GEN1> line 350."

This error shows up pretty early in the run, so I'm not sure if it has to do with step 3 or not. If you have any feedback for why my final output files are missing, please let me know. Thank you!

**Comment by maohlzj** [comment]
1. the output directory (-z option) should be created by the user yourself;
2. " SINE_Scan pipeline finished " just means that SINE_Scan finishes three steps, sometimes there is no result if SINE_Scan couldn't discover SINEs under its default SINE patterns in your genomic data;
3.  "Modification of non-creatable array value attempted, subscript -1 at ./PL_pipeline/RG_boundary.pl line 117, line 350." this is a bug in our algorithm which just means SINE_Scan access illegal memory, we have fixed it in own new version which will be uploaded soon after we finish its testings. Also it couldn't influence the SINE_Scan result;

Thank you for using SINE_Scan, I hope my answers above could help you. If you still have running error, please mail your error.log to me (my e-mail: mao.hongliang@163.com).

**Comment by kaylahardwick** [comment]
Thank you so much!
