### ISSUE TITLE
Can't locate object method "no_sequences" via package "Bio::SimpleAlign" at ./PL_pipeline/betterSeq-seeds.pl line 114, <GEN0> line 210.

### ISSUE THREAD

**Issue by zhangleigloria** [maohlzj/SINE_Scan#6]
Hi, when I was running the second step, the following error occurred. How should I solve it? Thank you very much!
Can't locate object method "no_sequences" via package "Bio::SimpleAlign" at ./PL_pipeline/betterSeq-seeds.pl line 114, <GEN0> line 210.
##################################
Workdir does not exists. build it.
Step One: Run SINE-Finder.
zhanjing
zhanjing
Finish Step One.
Time cost for SINE-Finder Module One:42204 wallclock secs ( 4.35 usr  1.08 sys + 69068.98 cusr 72.86 csys = 69147.27 CPU)
Build BlAST database for the genomic sequences.

Building a new DB, current time: 03/15/2020 23:29:32
New DB name:   Workdir/niechi.genome.fasta
New DB title:  Workdir/niechi.genome.fasta
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 12883 sequences in 87.037 seconds.
Time cost for Boundary fix:3.63403e+06 wallclock secs ( 0.00 usr  0.00 sys + 3173478.60 cusr 188213.56 csys = 3361692.16 CPU)
Step Two: SINE Verification.
Finish Step Two.
Time cost for Module Two :9031 wallclock secs ( 0.00 usr  0.01 sys + 3489.89 cusr 291.26 csys = 3781.16 CPU)
Step Three: Cannot read validated SINE candidate file. Stop.
If you ran Step 2, please check the file with the suffix of for_annotation.fa. Empty file means no good candidate was identified.
If you use your own validated SINEs (-a parameter), check this file.

**Comment by Zea1nfO** [comment]
@zhangleigloria
Hi
   Have you solved this issue? 
   If yes, can you tell how to fix this?
Thanks a lot
